import type { NextPage } from "next";
import Head from "next/head";
import HeaderComponent from "../components/header/header";
import style from "../styles/pages/home.module.css";
// import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MSys Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
      <HeaderComponent />
      <div className={style.container}>
        <div className={style.containerWrapper}>
          <div className={style.content}>
            <h1>MSys Crypto Games</h1>
            <div className={style.contentDescription}>
              {/* <p>
                Gaming has always been popular, but the new blockchain games are
                on the lips of everyone in the gaming industry. Blockchain games
                are not just video games that you play for the fun of it, they
                have the ability to make you some cool cash as a gamer. In
                simple terms, blockchain games are games built on blockchain
                technology.
              </p> */}
              <p>
                Back in 2022, it was an initiative to kick off Blockchain as a
                new-age technology at MSys. We quickly approached this and built
                a small team. Our next goal was to prepare a bunch of Blockchain
                Proof of Concepts, and as one of the ideas we ended up creating
                this platform.
                <br />
                <br />
                Goals of this platform:
                <br />
                1. This platform built on blockchain technology, is now capable
                to demonstrate our blockchain skills to existing customers, and
                newer prospects.
                <br />
                2. Also importantly this platform has few games, served by
                blockchain.
                <br />
                3. If you are keen to dive deep into Blockchain, to become a
                blockchain developer, this platform helps you. We hosted several
                basic to intermediate articles to begin; and will host many
                more.
                <br />
                We have the IPL 2023 ongoing, you can participate in guessing
                match winners from your favourite teams!!
                <br />
                <br />
                Please participate in our initiative and support us.
                <br />
                Thank you!
                <br />
              </p>
            </div>
            {/* <div className={style.sidebar}>
              <Link href="/betting">
                <div className={style.sidebarItem}>MSys&nbsp;Betting</div>
              </Link>
              <Link href="/lottery">
                <div className={style.sidebarItem}>MSys&nbsp;Lottery</div>
              </Link>
              <Link href="/nft">
                <div className={style.sidebarItem}>MSys&nbsp;NFT</div>
              </Link>
            </div> */}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
